### ISSUE TITLE
Stack trace at initialization is very costly

### ISSUE THREAD

**Issue by jespersmith** [ihmcrobotics/ihmc-yovariables#1]
When constructing a YoVariable it requests it's stack trace, which is a very expensive operation. Especially when making tests that create a lot of yovariables this slows down things a lot. 

We might want to remove the stack trace from the yovariable on initialization or come up with a faster method (Thread.currentThread.getStackTrace() might work)

**Comment by dljsjr** [comment]
Do we have benchmarks that one is faster than the other? I think it'd be about the same overhead either way and the stack trace for variable construction can be handy so I don't wanna get rid of it entirely. I use it a lot.

**Comment by SylvainBertrand** [comment]
The stack trace has been removed.
