### ISSUE TITLE
YoParameters and ReadOnly YoVariables

### ISSUE THREAD

**Issue by calvertdw** [ihmcrobotics/ihmc-yovariables#7]
It would be nice if the concepts of "read only" and "access protection"/"initialized from file"/"tuned by GUI only" were split up such that each YoVariable implements a ReadOnly interface and the other features could be built on top of regular YoVariables.

**Comment by jespersmith** [comment]
Calling something in a variable does imply that it can be varied. A YoVariableReadOnly interface would make no sense for a parameter, as it is not "variable".

**Comment by SylvainBertrand** [comment]
Isn't it what YoParameters are supposed to provide at the end?

**Comment by rjgriffin42** [comment]
I'm going to close this. part of me wants to make YoDouble extend DoubleParameter, such that you have an enforced read-only component.  The disadvantage of this is that we commonly cast DoubleParameter to YoDouble in tests so that we can set the value from code, which is a nice utility.
